package com.healthdietapp.ui.dashboard

import android.content.Intent
import android.animation.ObjectAnimator
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import androidx.recyclerview.widget.LinearLayoutManager
import com.healthdietapp.R
import com.healthdietapp.data.model.RecommendationResponseParcelable
import com.healthdietapp.databinding.FragmentDashboardBinding
import com.healthdietapp.utils.TokenManager
import com.healthdietapp.utils.hide
import com.healthdietapp.utils.show
import dagger.hilt.android.AndroidEntryPoint
import javax.inject.Inject

@AndroidEntryPoint
class DashboardFragment : Fragment() {

    private var _binding: FragmentDashboardBinding? = null
    private val binding get() = _binding!!

    private lateinit var foodAdapter: FoodAdapter

    @Inject
    lateinit var tokenManager: TokenManager

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentDashboardBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setupRecyclerView()

        val recommendation = arguments?.getParcelable<RecommendationResponseParcelable>("recommendation")
        if (recommendation != null) {
            displayResults(recommendation)
        }

        binding.swipeRefresh.setOnRefreshListener {
            binding.swipeRefresh.isRefreshing = false
        }

        binding.fabShare.setOnClickListener {
            recommendation?.let { shareResults(it) }
        }
    }

    private fun setupRecyclerView() {
        foodAdapter = FoodAdapter()
        binding.rvFoods.apply {
            layoutManager = LinearLayoutManager(requireContext())
            adapter = foodAdapter
        }
    }

    private fun displayResults(data: RecommendationResponseParcelable) {
        // BMI
        binding.tvBmiValue.text = String.format("%.2f", data.bmi)
        binding.tvBmiCategory.text = data.bmi_category
        binding.tvObesityLevel.text = data.predicted_obesity_level

        // BMI category color
        val bmiColor = when {
            data.bmi_category.contains("Underweight", ignoreCase = true) ->
                requireContext().getColor(R.color.bmi_underweight)
            data.bmi_category.contains("Normal", ignoreCase = true) ->
                requireContext().getColor(R.color.bmi_normal)
            data.bmi_category.contains("Overweight", ignoreCase = true) ->
                requireContext().getColor(R.color.bmi_overweight)
            else -> requireContext().getColor(R.color.bmi_obese)
        }
        binding.tvBmiCategory.setBackgroundColor(bmiColor)

        // Confidence score animation
        val animator = ObjectAnimator.ofInt(
            binding.progressConfidence,
            "progress",
            0,
            (data.confidence_score * 100).toInt()
        )
        animator.duration = 1000
        animator.start()
        binding.tvConfidenceScore.text = "Confidence: ${(data.confidence_score * 100).toInt()}%"

        // BMR and calories
        binding.tvBmrValue.text = "${data.bmr.toInt()} kcal"
        binding.tvCalorieTarget.text = "${data.daily_calorie_target} kcal"

        // Dietary notes
        binding.tvDietaryNotes.text = data.dietary_notes

        // Food list
        binding.shimmerLayout.stopShimmer()
        binding.shimmerLayout.hide()

        val foods = data.recommended_foods.take(10)
        if (foods.isEmpty()) {
            binding.tvEmptyFoods.show()
            binding.rvFoods.hide()
        } else {
            binding.tvEmptyFoods.hide()
            binding.rvFoods.show()
            foodAdapter.submitList(foods)
        }
    }

    private fun shareResults(data: RecommendationResponseParcelable) {
        val shareText = """
            🏥 Health Analysis Report - HealthDiet AI
            
            📊 BMI: ${String.format("%.2f", data.bmi)} (${data.bmi_category})
            🎯 Obesity Level: ${data.predicted_obesity_level}
            🔥 BMR: ${data.bmr.toInt()} kcal/day
            🍽️ Daily Calorie Target: ${data.daily_calorie_target} kcal/day
            
            📝 Dietary Notes:
            ${data.dietary_notes}
            
            Generated by HealthDiet AI
        """.trimIndent()

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, shareText)
            putExtra(Intent.EXTRA_SUBJECT, "My Health Analysis Report")
        }
        startActivity(Intent.createChooser(shareIntent, "Share Health Report"))
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
