#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, you may
#       want to try it by invoking with that shell.
#       Like: sh /path/to/gradlew
#
#   (2) The GraalVM native image tests in the Gradle suite will fail for previous
#       versions of GraalVM native image (before version 20.3) as it does not
#       properly support "chmod +x" on files created in the container.
#
##############################################################################

if [ "$(uname)" = "Darwin" ] ; then
    APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P )
    APP_NAME="Gradle"
    # Use the maximum available, or set MAX_FD != -1 to use that
    MAX_FD=$( (
        ulimit -H -n 2>/dev/null || echo $MAX_FD
    ) )
else
    APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
    APP_NAME="Gradle"
    # Use the maximum available, or set MAX_FD != -1 to use that
    MAX_FD=$( (
        ulimit -H -n 2>/dev/null || echo $MAX_FD
    ) )
fi
# ... rest of script would be quite long, using the standard Gradle wrapper template

